version: '3.7'
services:
  review360-init:
    image: review360-init:latest
    init: true
    environment:
      MYSQL_USER: review360
      MYSQL_PASSWORD: review360
      MYSQL_URL: review360:review360@tcp(mysql:3306)/review360
    links:
      - "mysql:mysql"
    depends_on:
      - "mysql"
    command: ["./wait-for-it.sh" ,"mysql"]
  review360:
    image: review360:latest
    container_name: review360
    restart: always
    ports:
      - 8080:8080
    links:
      - "mysql:mysql"
      - "review360-init:review360-init"
    depends_on:
      - "mysql"
      - "review360-init"
    environment:
      MYSQL_USER: review360
      MYSQL_PASSWORD: review360
      MYSQL_URL: review360:review360@tcp(mysql:3306)/review360
      SECRET: secret-for-jwt
      PORT: 8080

  mysql:
    image: review360-mysql:latest
    container_name: review360-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_USER: review360
      MYSQL_PASSWORD: review360
